server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fastapi
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container

      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      - source_labels: [__meta_docker_container_image]
        target_label: image

      - source_labels: [__meta_docker_container_log_stream]
        target_label: __log_stream__

      - source_labels: [__meta_docker_container_name]
        target_label: container

      - action: replace
        target_label: job
        replacement: fastapi

    pipeline_stages:
      - json:
          expressions:
            type: type
            method: method
            path: path
            status_code: status_code
            duration_ms: duration_ms
            client_ip: client_ip
            user_agent: user_agent
      - labels:
          type:
          method:
          path:
          status_code:
      - output:
          source: msg
